name: Auto Build App Store

on:
  release:
    types: [published]
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Khởi tạo Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Tải file IPA từ GitHub Release (Latest)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p apps
          curl -sH "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | grep "browser_download_url.*ipa" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi - -P apps/

      - name: Chạy Script xử lý IPA
        run: python build.py

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dữ liệu
        # Đã nâng cấp lên v3 để vượt qua lỗi chặn của GitHub
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy lên GitHub Pages
        # Đã nâng cấp lên v4
        uses: actions/deploy-pages@v4
