name: Auto Build Multi-Page App Store

# Kích hoạt khi Release được Tạo mới (published) hoặc Cập nhật sửa đổi (edited)
on:
  release:
    types: [published, edited]
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Khởi tạo Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Chạy hệ thống Quét App và Tạo Web
        # Cấp quyền token để Python gọi API lấy danh sách file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python build.py

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Website
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy lên mạng
        uses: actions/deploy-pages@v4
